language: bash
git:
    submodules: false
before_script:
    - gem install homesick
script:
    - homesick clone "matthiasvegh/dotfiles"
    - homesick symlink -f "dotfiles"
    - homesick rc --force "dotfiles"
