language: bash
git:
    submodules: false
before_script:
    - gem install homesick
script:
    - homesick clone --force "matthiasvegh/dotfiles"
    - homesick symlink --force "dotfiles"
    - homesick rc --force "dotfiles"
